# 50 QA pairs for RAG evaluation

QA_PAIRS = [
    {"question": "What are the three main types of machine learning?", "answer": "The three main types of machine learning are supervised learning, unsupervised learning, and reinforcement learning."},
    {"question": "What is overfitting in machine learning?", "answer": "Overfitting occurs when a model performs well on training data but poorly on unseen test data by learning noise rather than the underlying pattern."},
    {"question": "Explain the bias-variance tradeoff.", "answer": "The bias-variance tradeoff is the balance between errors from overly simple assumptions (bias) and excessive sensitivity to fluctuations in training data (variance)."},
    {"question": "How does regularization prevent overfitting?", "answer": "Regularization prevents overfitting by adding a penalty term to the loss function, which constrains the magnitude of the model's weights."},
    {"question": "What is cross-validation?", "answer": "Cross-validation is a technique for assessing how a model generalizes to an independent dataset by partitioning data into training and testing subsets."},
    {"question": "What is backpropagation?", "answer": "Backpropagation is the algorithm used for training neural networks by calculating the gradient of the loss function with respect to each weight."},
    {"question": "What are Convolutional Neural Networks primarily used for?", "answer": "Convolutional Neural Networks (CNNs) are primarily used for image processing and computer vision tasks."},
    {"question": "How do LSTM networks address the vanishing gradient problem?", "answer": "LSTM networks use specialized gates (input, forget, and output) to regulate the flow of information over long sequences, mitigating vanishing gradients."},
    {"question": "What activation functions are commonly used in neural networks?", "answer": "Common activation functions include ReLU (Rectified Linear Unit), Sigmoid, and Tanh."},
    {"question": "What is the role of pooling layers in CNNs?", "answer": "Pooling layers in CNNs reduce spatial dimensions and computation by downsampling the feature maps."},
    {"question": "What is the transformer architecture?", "answer": "The transformer architecture relies on self-attention mechanisms to process sequences in parallel, widely used for state-of-the-art NLP tasks."},
    {"question": "What are word embeddings?", "answer": "Word embeddings are vector representations of words where semantically similar words are close together in the vector space."},
    {"question": "What is transfer learning in NLP?", "answer": "Transfer learning in NLP involves pre-training a large model on a massive dataset and then fine-tuning it for a specific task."},
    {"question": "How does BERT handle language understanding?", "answer": "BERT handles language understanding by processing text bidirectionally, looking at context from both left and right directions."},
    {"question": "What is self-attention in transformers?", "answer": "Self-attention allows a transformer model to weight the importance of different words in a sentence regardless of their distance."},
    {"question": "What is GPT and how is it trained?", "answer": "GPT (Generative Pre-trained Transformer) is a decoder-only model trained to predict the next word in a sequence."},
    {"question": "What is instruction tuning?", "answer": "Instruction tuning is a method of fine-tuning LLMs to follow specific human instructions more effectively."},
    {"question": "What is RLHF?", "answer": "RLHF stands for Reinforcement Learning from Human Feedback, a method to align LLMs with human preferences."},
    {"question": "What is chain-of-thought prompting?", "answer": "Chain-of-thought prompting encourages LLMs to show their step-by-step reasoning process to improve accuracy on complex tasks."},
    {"question": "What is the context length of GPT-4?", "answer": "GPT-4 has a significantly larger context length than previous versions, allowing it to process much longer documents."},
    {"question": "What is Retrieval-Augmented Generation?", "answer": "Retrieval-Augmented Generation (RAG) is a technique that combines LLMs with external knowledge retrieval to provide more accurate answers."},
    {"question": "What are the main components of a RAG pipeline?", "answer": "Main components include a data source, embedding model, vector database, retriever, and an LLM."},
    {"question": "What is dense retrieval?", "answer": "Dense retrieval uses vector embeddings to find documents based on semantic meaning rather than keyword matching."},
    {"question": "Why is chunking strategy important in RAG?", "answer": "Chunking strategy determines the context size of retrieved information; balancing context and relevance is critical."},
    {"question": "What advanced RAG techniques exist beyond basic retrieval?", "answer": "Advanced techniques include recursive retrieval, reranking, and hybrid search methods."},
    {"question": "What are vector databases used for?", "answer": "Vector databases are used to store and efficiently search high-dimensional vector embeddings."},
    {"question": "What is FAISS?", "answer": "FAISS (Facebook AI Similarity Search) is a library for efficient similarity search and clustering of dense vectors."},
    {"question": "How do text embeddings capture semantic meaning?", "answer": "Text embeddings capture semantic meaning by mapping words or sentences into a high-dimensional space where similar concepts are close."},
    {"question": "What is HNSW?", "answer": "HNSW (Hierarchical Navigable Small World) is a graph-based algorithm for approximate nearest neighbor search."},
    {"question": "What is hybrid search in vector databases?", "answer": "Hybrid search combines keyword-based BM25 search with vector-based semantic search for better accuracy."},
    {"question": "What is LangChain?", "answer": "LangChain is a framework for building LLM-powered applications with components like chains, memory, and retrievers."},
    {"question": "What is LangChain Expression Language (LCEL)?", "answer": "LCEL is a declarative language for composing LangChain components using the pipe operator (|)."},
    {"question": "What is LangGraph?", "answer": "LangGraph is an extension of LangChain for building stateful, multi-agent LLM applications with cycles."},
    {"question": "What memory types does LangChain support?", "answer": "LangChain supports various memory types including Buffer, Summary, and Entity memory to maintain conversation state."},
    {"question": "What are LangChain retrievers?", "answer": "Retrievers are LangChain components that fetch relevant documents from a data source based on a query."},
    {"question": "What is LangSmith?", "answer": "LangSmith is a platform for debugging, testing, and monitoring LLM applications via detailed execution traces."},
    {"question": "What information do LangSmith traces capture?", "answer": "LangSmith traces capture inputs, outputs, latency, token usage, and intermediate steps of LLM executions."},
    {"question": "What is the LangSmith Prompt Hub?", "answer": "The Prompt Hub is a repository for versioned prompt templates that can be managed and tested independently of code."},
    {"question": "How does LangSmith help monitor production LLM applications?", "answer": "It helps monitor performance, identify bottlenecks, and gather feedback for continuous improvement."},
    {"question": "What are LangSmith datasets used for?", "answer": "Datasets are used for systematic testing and evaluation of LLM pipelines against known ground truths."},
    {"question": "What is RAGAS?", "answer": "RAGAS is a framework for automated evaluation of RAG pipelines using specialized metrics."},
    {"question": "How does RAGAS compute faithfulness?", "answer": "Faithfulness measures how well the generated answer is supported by the retrieved context."},
    {"question": "What is answer relevancy in RAGAS?", "answer": "Answer relevancy measures how pertinent the generated answer is to the user's initial question."},
    {"question": "What is context recall in RAGAS?", "answer": "Context recall measures whether the retrieved context contains all the information needed to answer the question."},
    {"question": "What inputs does RAGAS evaluation require?", "answer": "RAGAS requires questions, generated answers, retrieved contexts, and (optionally) ground-truth answers."},
    {"question": "What is Guardrails AI?", "answer": "Guardrails AI is a framework for validating LLM outputs against safety and quality constraints."},
    {"question": "What is PII and why is it important to detect in LLM responses?", "answer": "PII is Personally Identifiable Information; detecting it is crucial for privacy and data protection compliance."},
    {"question": "What does structured output validation ensure?", "answer": "It ensures that the LLM output follows a specific format, such as valid JSON, for downstream processing."},
    {"question": "What is Constitutional AI?", "answer": "Constitutional AI is an approach to align LLMs using a set of written principles or a 'constitution' for ethical behavior."},
    {"question": "What are common AI safety concerns with LLMs?", "answer": "Common concerns include hallucinations, bias, toxic content generation, and leakage of sensitive information."},
]
